// 02-react-exercise/index.js
import * as React from "react";
import * as ReactDOM from "react-dom";
import singleSpaReact from "single-spa-react";
import { registerApplication, start } from "single-spa";
import Root from "./Root";

const app = singleSpaReact({
  React,
  ReactDOM,
  rootComponent: Root,
});

registerApplication({
  name: "react-app",
  app,
  activeWhen: ["/"],
});

start();

// 02-angular-exercise/index.ts
import { singleSpaAngular } from "single-spa-angular";
import { registerApplication, start } from "single-spa";
import { platformBrowserDynamic } from "@angular/platform-browser-dynamic";
import { NgZone } from "@angular/core";
import { AppModule } from "./src/app.module";

const app = singleSpaAngular({
  bootstrapFunction() {
    return platformBrowserDynamic().bootstrapModule(AppModule);
  },
  template: "<app-root>",
  NgZone,
});

registerApplication({
  name: "angular-app",
  app,
  activeWhen: ["/"],
});

start();
